USE master
GO
IF DB_ID('PTTK_TTLT_ACCI') IS NOT NULL
	DROP DATABASE PTTK_TTLT_ACCI
GO

CREATE DATABASE PTTK_TTLT_ACCI
GO

USE PTTK_TTLT_ACCI
GO

-- Tạo bảng
-- Bảng KHACH_HANG
CREATE TABLE KHACH_HANG (
	ID INT IDENTITY(1,1),
    MaKH AS 
		'KHHG' + RIGHT('000000' + CAST(ID AS VARCHAR(6)), 6) 
		PERSISTED PRIMARY KEY,
    TenKH NVARCHAR(100),
    LoaiKH NVARCHAR(12),
    SDT CHAR(12),
    DiaChi NVARCHAR(100),
    Email VARCHAR(100)
);

-- Bảng THI_SINH
CREATE TABLE THI_SINH (
	ID INT IDENTITY(1,1),
    MaTS AS 
		'THSH' + RIGHT('000000' + CAST(ID AS VARCHAR(6)), 6) 
		PERSISTED PRIMARY KEY,
    TenTS NVARCHAR(100),
    NgaySinh DATE,
    CCCD CHAR(12),
    MaKH VARCHAR(10)
);

-- Bảng NHAN_VIEN
CREATE TABLE NHAN_VIEN (
	ID INT IDENTITY(1,1),
    MaNV AS 
		'NHVN' + RIGHT('000000' + CAST(ID AS VARCHAR(6)), 6) 
		PERSISTED PRIMARY KEY,
    TenNhanVien NVARCHAR(100),
    NgaySinh DATE,
    Email VARCHAR(100),
    SDT CHAR(12),
    DiaChi NVARCHAR(100),
    CCCD CHAR(12),
    LoaiNhanVien NVARCHAR(12)
);

-- Bảng PHONG_THI
CREATE TABLE PHONG_THI (
	ID INT IDENTITY(1,1),
    MaPT AS 
		'PHTI' + RIGHT('000000' + CAST(ID AS VARCHAR(6)), 6) 
		PERSISTED PRIMARY KEY,
    SucChua INT,
    TrangThai NVARCHAR(12)
);

-- Bảng LOAI_CHUNG_CHI
CREATE TABLE LOAI_CHUNG_CHI (
	ID INT IDENTITY(1,1),
    MaLCC AS 
		'LOCC' + RIGHT('000000' + CAST(ID AS VARCHAR(6)), 6) 
		PERSISTED PRIMARY KEY,
    TenLoaiChungChi NVARCHAR(100),
	LinhVucChungChi NVARCHAR(100),
    DiemChuan FLOAT,
    ThoiHan INT -- tháng
);

-- Bảng XEP_HANG_CHUNG_CHI
CREATE TABLE XEP_HANG_CHUNG_CHI (
    MaLCC VARCHAR(10),
    XepHang VARCHAR(10),
    DiemSan FLOAT,
    DiemTran FLOAT,
    PRIMARY KEY (MaLCC, XepHang)
);

-- Bảng LICH_THI
CREATE TABLE LICH_THI (
	ID INT IDENTITY(1,1),
    MaLT AS 
		'LICH' + RIGHT('000000' + CAST(ID AS VARCHAR(6)), 6) 
		PERSISTED PRIMARY KEY,
    NgayGioThi DATETIME,
    SoLuongToiDa INT,
	SoLuongDaDangKy INT,
    LoaiChungChi VARCHAR(10),    
    MaPT VARCHAR(10)
);

-- Bảng NHAN_VIEN_GIAM_THI_LICH_THI
CREATE TABLE NHAN_VIEN_GIAM_THI_LICH_THI (
    MaLT VARCHAR(10),
    MaNV VARCHAR(10),
    VaiTro NVARCHAR(100), -- Ví dụ: Giám thị chính, Giám thị hành lang, Thư ký, ...
    PRIMARY KEY (MaLT, MaNV)
);

-- Bảng PHIEU_DANG_KY
CREATE TABLE PHIEU_DANG_KY (
	ID INT IDENTITY(1,1),
    MaPDK AS 
		'PHDK' + RIGHT('000000' + CAST(ID AS VARCHAR(6)), 6) 
		PERSISTED PRIMARY KEY,
    NgayLapPDK DATE,
    TrangThai NVARCHAR(12),
    HanThanhToan DATE,
    MaLCC VARCHAR(10),
    MaLT VARCHAR(10),
    MaKH VARCHAR(10),
    MaTS VARCHAR(10),
    MaNVTiepNhan VARCHAR(10)
);

-- Bảng HOA_DON
CREATE TABLE HOA_DON (
	ID INT IDENTITY(1,1),
    MaHD AS 
		'HDON' + RIGHT('000000' + CAST(ID AS VARCHAR(6)), 6) 
		PERSISTED PRIMARY KEY,
    NgayGioThanhToan DATETIME,
    SoTienThanhToan FLOAT,
    HinhThucThanhToan NVARCHAR(100),
    ChietKhau FLOAT,
    MaPDK VARCHAR(10),
    MaNVKeToan VARCHAR(10)
);

-- Bảng PHIEU_DU_THI
CREATE TABLE PHIEU_DU_THI (
	ID INT IDENTITY(1,1),
    MaPDT AS 
		'PHDT' + RIGHT('000000' + CAST(ID AS VARCHAR(6)), 6) 
		PERSISTED PRIMARY KEY,
    NgayPhatHanh DATE,
    TrangThai NVARCHAR(12),
    ThoiGianThi DATETIME,
    DiaDiemThi NVARCHAR(100),
    MaTS VARCHAR(10),
    MaLT VARCHAR(10),
    MaHD VARCHAR(10)
);

-- Bảng KET_QUA_THI
CREATE TABLE KET_QUA_THI (
	ID INT IDENTITY(1,1),
    MaKQT AS 
		'KQTH' + RIGHT('000000' + CAST(ID AS VARCHAR(6)), 6) 
		PERSISTED PRIMARY KEY,
    DiemSo FLOAT,
    NgayCoDiem DATE,
    MaTS VARCHAR(10),
    MaLCC VARCHAR(10),
	MaPDT VARCHAR(10)
);

-- Bảng CHUNG_CHI
CREATE TABLE CHUNG_CHI (
	ID INT IDENTITY(1,1),
    MaCC AS 
		'CHCH' + RIGHT('000000' + CAST(ID AS VARCHAR(6)), 6) 
		PERSISTED PRIMARY KEY,
    DiemSo FLOAT,
    XepHang VARCHAR(10),
    NgayCap DATE,
    NgayHetHan DATE,
	TrangThai NVARCHAR(12),
    MaKQT VARCHAR(10),
    MaTS VARCHAR(10),
    MaLCC VARCHAR(10)
);

-- Bảng PHIEU_DU_THI_GIA_HAN
CREATE TABLE PHIEU_DU_THI_GIA_HAN (
	ID INT IDENTITY(1,1),
    MaPDTGH AS 
		'DTGH' + RIGHT('000000' + CAST(ID AS VARCHAR(6)), 6) 
		PERSISTED PRIMARY KEY,
    MaPDT VARCHAR(10),
    SoLanConLai INT,
    HanGiaHan DATE
);

-- Bảng YEU_CAU_GIA_HAN
CREATE TABLE YEU_CAU_GIA_HAN (
	ID INT IDENTITY(1,1),
    MaYCGH AS 
		'YCGH' + RIGHT('000000' + CAST(ID AS VARCHAR(6)), 6) 
		PERSISTED PRIMARY KEY,
    NgayYeuCauGiaHan DATE,
    LyDoGiaHan NVARCHAR(100),
    PhiGiaHan FLOAT,
    MaPDT VARCHAR(10)
);

-- Bảng HOA_DON_GIA_HAN
CREATE TABLE HOA_DON_GIA_HAN (
	ID INT IDENTITY(1,1),
    MaHDGH AS 
		'HDGH' + RIGHT('000000' + CAST(ID AS VARCHAR(6)), 6) 
		PERSISTED PRIMARY KEY,
    NgayGioThanhToan DATETIME,
    SoTienThanhToan FLOAT,
    HinhThucThanhToan NVARCHAR(100),
    TrangThai NVARCHAR(12),
    MaPDT VARCHAR(10),
    MaYCGH VARCHAR(10),
    MaNVKeToan VARCHAR(10)
);

-- Tạo khóa ngoại
/*  
	HOA_DON_GIA_HAN,
    PHIEU_DU_THI_GIA_HAN,
    YEU_CAU_GIA_HAN,
*/
-- THI_SINH -> KHACH_HANG
ALTER TABLE THI_SINH ADD CONSTRAINT FK_THI_SINH_KHACH_HANG
FOREIGN KEY (MaKH) REFERENCES KHACH_HANG(MaKH);

-- XEP_HANG_CHUNG_CHI -> LOAI_CHUNG_CHI
ALTER TABLE XEP_HANG_CHUNG_CHI ADD CONSTRAINT FK_XHCC_LOAI_CHUNG_CHI
FOREIGN KEY (MaLCC) REFERENCES LOAI_CHUNG_CHI(MaLCC);

-- LICH_THI -> PHONG_THI
ALTER TABLE LICH_THI ADD CONSTRAINT FK_LICH_THI_PHONG_THI
FOREIGN KEY (MaPT) REFERENCES PHONG_THI(MaPT);
-- LICH_THI -> LOAI_CHUNG_CHI
ALTER TABLE LICH_THI ADD CONSTRAINT FK_LICH_THI_LOAI_CHUNG_CHI
FOREIGN KEY (LoaiChungChi) REFERENCES LOAI_CHUNG_CHI(MaLCC);

-- NHAN_VIEN_GIAM_THI_LICH_THI -> LICH_THI
ALTER TABLE NHAN_VIEN_GIAM_THI_LICH_THI ADD CONSTRAINT FK_NVGTLT_LICH_THI
FOREIGN KEY (MaLT) REFERENCES LICH_THI(MaLT);
-- NHAN_VIEN_GIAM_THI_LICH_THI -> NHAN_VIEN
ALTER TABLE NHAN_VIEN_GIAM_THI_LICH_THI ADD CONSTRAINT FK_NVGTLT_NHAN_VIEN
FOREIGN KEY (MaNV) REFERENCES NHAN_VIEN(MaNV);

-- PHIEU_DANG_KY -> LOAI_CHUNG_CHI
ALTER TABLE PHIEU_DANG_KY ADD CONSTRAINT FK_PDK_LOAI_CHUNG_CHI
FOREIGN KEY (MaLCC) REFERENCES LOAI_CHUNG_CHI(MaLCC);
-- PHIEU_DANG_KY -> LICH_THI
ALTER TABLE PHIEU_DANG_KY ADD CONSTRAINT FK_PDK_LICH_THI
FOREIGN KEY (MaLT) REFERENCES LICH_THI(MaLT);
-- PHIEU_DANG_KY -> KHACH_HANG
ALTER TABLE PHIEU_DANG_KY ADD CONSTRAINT FK_PDK_KHACH_HANG
FOREIGN KEY (MaKH) REFERENCES KHACH_HANG(MaKH);
-- PHIEU_DANG_KY -> THI_SINH
ALTER TABLE PHIEU_DANG_KY ADD CONSTRAINT FK_PDK_THI_SINH
FOREIGN KEY (MaTS) REFERENCES THI_SINH(MaTS);
-- PHIEU_DANG_KY -> NHAN_VIEN (MaNVTiepNhan)
ALTER TABLE PHIEU_DANG_KY ADD CONSTRAINT FK_PDK_NHAN_VIEN_TIEP_NHAN
FOREIGN KEY (MaNVTiepNhan) REFERENCES NHAN_VIEN(MaNV);

-- HOA_DON -> PHIEU_DANG_KY
ALTER TABLE HOA_DON ADD CONSTRAINT FK_HOA_DON_PHIEU_DANG_KY
FOREIGN KEY (MaPDK) REFERENCES PHIEU_DANG_KY(MaPDK);
-- HOA_DON -> NHAN_VIEN (MaNVKeToan)
ALTER TABLE HOA_DON ADD CONSTRAINT FK_HOA_DON_NHAN_VIEN_KE_TOAN
FOREIGN KEY (MaNVKeToan) REFERENCES NHAN_VIEN(MaNV);

-- PHIEU_DU_THI -> THI_SINH
ALTER TABLE PHIEU_DU_THI ADD CONSTRAINT FK_PDT_THI_SINH
FOREIGN KEY (MaTS) REFERENCES THI_SINH(MaTS);
-- PHIEU_DU_THI -> LICH_THI
ALTER TABLE PHIEU_DU_THI ADD CONSTRAINT FK_PDT_LICH_THI
FOREIGN KEY (MaLT) REFERENCES LICH_THI(MaLT);
-- PHIEU_DU_THI -> HOA_DON
ALTER TABLE PHIEU_DU_THI ADD CONSTRAINT FK_PDT_HOA_DON
FOREIGN KEY (MaHD) REFERENCES HOA_DON(MaHD);

-- KET_QUA_THI -> THI_SINH
ALTER TABLE KET_QUA_THI ADD CONSTRAINT FK_KQT_THI_SINH
FOREIGN KEY (MaTS) REFERENCES THI_SINH(MaTS);
-- KET_QUA_THI -> LOAI_CHUNG_CHI
ALTER TABLE KET_QUA_THI ADD CONSTRAINT FK_KQT_LOAI_CHUNG_CHI
FOREIGN KEY (MaLCC) REFERENCES LOAI_CHUNG_CHI(MaLCC);
-- KET_QUA_THI -> PHIEU_DU_THI
ALTER TABLE KET_QUA_THI ADD CONSTRAINT FK_KQT_PHIEU_DU_THI
FOREIGN KEY (MaPDT) REFERENCES PHIEU_DU_THI(MaPDT);

-- CHUNG_CHI -> KET_QUA_THI
ALTER TABLE CHUNG_CHI ADD CONSTRAINT FK_CHUNG_CHI_KET_QUA_THI
FOREIGN KEY (MaKQT) REFERENCES KET_QUA_THI(MaKQT);
-- CHUNG_CHI -> THI_SINH
ALTER TABLE CHUNG_CHI ADD CONSTRAINT FK_CHUNG_CHI_THI_SINH
FOREIGN KEY (MaTS) REFERENCES THI_SINH(MaTS);
-- CHUNG_CHI -> LOAI_CHUNG_CHI
ALTER TABLE CHUNG_CHI ADD CONSTRAINT FK_CHUNG_CHI_LOAI_CHUNG_CHI
FOREIGN KEY (MaLCC) REFERENCES LOAI_CHUNG_CHI(MaLCC);

-- PHIEU_DU_THI_GIA_HAN -> PHIEU_DU_THI
ALTER TABLE PHIEU_DU_THI_GIA_HAN ADD CONSTRAINT FK_PDTGH_PHIEU_DU_THI
FOREIGN KEY (MaPDT) REFERENCES PHIEU_DU_THI(MaPDT);

-- YEU_CAU_GIA_HAN -> PHIEU_DU_THI
ALTER TABLE YEU_CAU_GIA_HAN ADD CONSTRAINT FK_YCGH_PHIEU_DU_THI
FOREIGN KEY (MaPDT) REFERENCES PHIEU_DU_THI(MaPDT);

-- HOA_DON_GIA_HAN -> PHIEU_DU_THI
ALTER TABLE HOA_DON_GIA_HAN ADD CONSTRAINT FK_HDGH_PHIEU_DU_THI
FOREIGN KEY (MaPDT) REFERENCES PHIEU_DU_THI(MaPDT);
-- HOA_DON_GIA_HAN -> YEU_CAU_GIA_HAN
ALTER TABLE HOA_DON_GIA_HAN ADD CONSTRAINT FK_HDGH_YEU_CAU_GIA_HAN
FOREIGN KEY (MaYCGH) REFERENCES YEU_CAU_GIA_HAN(MaYCGH);
-- HOA_DON_GIA_HAN -> NHAN_VIEN (MaNVKeToan)
ALTER TABLE HOA_DON_GIA_HAN ADD CONSTRAINT FK_HDGH_NHAN_VIEN
FOREIGN KEY (MaNVKeToan) REFERENCES NHAN_VIEN(MaNV);

/*
SELECT * FROM KHACH_HANG;
SELECT * FROM THI_SINH;
SELECT * FROM NHAN_VIEN;

SELECT * FROM LOAI_CHUNG_CHI;
SELECT * FROM XEP_HANG_CHUNG_CHI;

SELECT * FROM PHONG_THI;
SELECT * FROM LICH_THI;
SELECT * FROM NHAN_VIEN_GIAM_THI_LICH_THI;

SELECT * FROM PHIEU_DANG_KY;
SELECT * FROM HOA_DON;
SELECT * FROM PHIEU_DU_THI;

SELECT * FROM KET_QUA_THI;
SELECT * FROM CHUNG_CHI;

SELECT * FROM PHIEU_DU_THI_GIA_HAN;
SELECT * FROM YEU_CAU_GIA_HAN;
SELECT * FROM HOA_DON_GIA_HAN;
*/
